name: Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install yarn
        run: npm install -g yarn
        shell: bash
      - name: Install hardhat packages
        run: |
          cd hardhat
          yarn install
        shell: bash
      - name: Install front packages
        run: |
          cd client
          yarn install
        shell: bash
      - name: Build smart contract
        run: |
          cd hardhat
          yarn build
      - name: Deploy smart contract
        run: |
          cd hardhat
          yarn dev &
          yarn deploy:hardhat
      - name: Build front
        run: |
          cd client
          yarn build
