name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm install -g yarn
        shell: bash
      - run: |
          cd hardhat
          yarn install
        shell: bash
      - name: Run Tests
        run: yarn test
      - name: Run Coverage
        run: yarn coverage
